build:
  environment:
    php: '8.3.3'
  nodes:
    analysis:
      tests:
        override:
          - command: 'vendor/bin/php-cs-fixer fix --dry-run --diff --stop-on-violation'
          - command: 'vendor/bin/phpstan analyse'
          - command: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
            coverage:
              file: 'build/logs/clover.xml'
              format: 'php-clover'

checks:
  php:
    code_rating: true
    duplication: true