build:
  environment:
    php: '8.3'
  nodes:
    analysis:
      tests:
        override:
          - command: 'vendor/bin/php-cs-fixer fix --dry-run --diff --stop-on-violation'
            analysis:
              never_exec: true
          - command: 'vendor/bin/phpstan analyse'
            analysis:
              never_exec: true

checks:
  php:
    code_rating: true
    duplication: true

tools:
  phpunit:
    config_file: 'phpunit.xml.dist'